# Generated by Django 5.1.4 on 2025-05-05 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centros',
            fields=[
                ('idcentro', models.AutoField(db_column='IdCentro', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NombreCentro', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'centros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('iddispositivo', models.AutoField(db_column='IdDispositivo', primary_key=True, serialize=False)),
                ('sn', models.CharField(db_column='SnDispositivo', max_length=50, unique=True)),
                ('imagen', models.ImageField(blank=True, db_column='ImagenDispositivo', max_length=50, null=True, upload_to='images/devices/')),
                ('documento', models.FileField(blank=True, db_column='DocumentoDispositivo', max_length=50, null=True, upload_to='docs/devices/')),
            ],
            options={
                'db_table': 'dispositivos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DispositivosMarca',
            fields=[
                ('idmarcadispositivo', models.AutoField(db_column='IdMarcaDispositivo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='utf8mb4_spanish_ci', db_column='NombreMarcaDispositivo', max_length=20)),
            ],
            options={
                'db_table': 'dispositivos_marca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DispositivosTipo',
            fields=[
                ('idtipodispositivo', models.AutoField(db_column='IdTipoDispositivo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NombreTipoDispositivo', max_length=20, unique=True)),
            ],
            options={
                'db_table': 'dispositivos_tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentoTipo',
            fields=[
                ('idtipodocumento', models.AutoField(db_column='IdTipoDocumento', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NombreTipoDocumento', max_length=10, unique=True)),
            ],
            options={
                'db_table': 'documento_tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fichas',
            fields=[
                ('idficha', models.AutoField(db_column='IdFicha', primary_key=True, serialize=False)),
                ('numero', models.CharField(db_column='NumeroFicha', max_length=10, unique=True)),
            ],
            options={
                'db_table': 'fichas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FichasNombre',
            fields=[
                ('idfichanombre', models.AutoField(db_column='IdFichaNombre', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NombreFicha', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'fichas_nombre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FichasTipo',
            fields=[
                ('idtipoficha', models.AutoField(db_column='IdTipoFicha', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NombreTipoFicha', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'fichas_tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('idingreso', models.AutoField(db_column='IdIngreso', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='FechaIngreso')),
                ('horaingreso', models.TimeField(db_column='HoraIngreso')),
            ],
            options={
                'db_table': 'ingresos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('idjornada', models.AutoField(db_column='IdJornada', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NombreJornada', max_length=10, unique=True)),
            ],
            options={
                'db_table': 'jornada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('idrol', models.AutoField(db_column='IdRol', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NombreRol', max_length=20, unique=True)),
                ('descripcion', models.TextField(db_column='DescripcionRol')),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salidas',
            fields=[
                ('idsalida', models.AutoField(db_column='IdSalida', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='FechaSalida')),
                ('horasalida', models.TimeField(db_column='HoraSalida')),
            ],
            options={
                'db_table': 'salidas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sanciones',
            fields=[
                ('idsancion', models.AutoField(db_column='IdSancion', primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(db_column='Fecha_Inicio_Sancion')),
                ('fecha_fin', models.DateField(db_column='Fecha_Fin_Sancion')),
                ('estado', models.IntegerField(db_column='EstadoSancion')),
                ('descripcion', models.TextField(db_column='DescripcionSancion')),
            ],
            options={
                'db_table': 'sanciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idusuario', models.AutoField(db_column='IdUsuario', primary_key=True, serialize=False)),
                ('nombres', models.CharField(db_column='NombresUsuario', max_length=50)),
                ('apellidos', models.CharField(db_column='ApellidosUsuario', max_length=50)),
                ('documento', models.CharField(db_column='DocumentoUsuario', max_length=10, unique=True)),
                ('telefono', models.CharField(db_column='TelefonoUsuario', max_length=10, unique=True)),
                ('correo', models.CharField(blank=True, db_column='CorreoUsuario', max_length=100, null=True, unique=True)),
                ('imagen', models.ImageField(db_column='ImagenUsuario', max_length=50, upload_to='images/users/')),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('idvehiculo', models.AutoField(db_column='IdVehiculo', primary_key=True, serialize=False)),
                ('placa', models.CharField(blank=True, db_column='PlacaVehiculo', default='000-000', max_length=7, null=True, unique=True)),
                ('modelo', models.CharField(blank=True, db_column='ModeloVehiculo', default=None, max_length=4, null=True)),
                ('imagen', models.ImageField(blank=True, db_column='ImagenVehiculo', max_length=50, null=True, upload_to='images/vehicles/')),
            ],
            options={
                'db_table': 'vehiculos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehiculosMarca',
            fields=[
                ('idmarcavehiculo', models.AutoField(db_column='IdMarcaVehiculo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NombreMarcaVehiculo', max_length=20)),
            ],
            options={
                'db_table': 'vehiculos_marca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehiculosTipo',
            fields=[
                ('idtipovehiculo', models.AutoField(db_column='IdTipoVehiculo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NombreTipoVehiculo', max_length=20, unique=True)),
            ],
            options={
                'db_table': 'vehiculos_tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FichasXAprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.usuarios')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.fichas')),
            ],
        ),
    ]
