# Generated by Django 5.2 on 2025-06-04 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_alter_usuarios_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='centro',
            field=models.ForeignKey(blank=True, db_column='IdCentro', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.centros'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='ficha',
            field=models.ForeignKey(blank=True, db_column='IdFicha', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.fichas'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='rol',
            field=models.ForeignKey(db_column='IdRol', default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.roles'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='tipodocumento',
            field=models.ForeignKey(db_column='IdTipoDocumento', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.documentotipo'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='imagen',
            field=models.ImageField(db_column='ImagenUsuario', max_length=50, upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefono',
            field=models.CharField(blank=True, db_column='TelefonoUsuario', default=None, max_length=10, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/extras/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='administrator.ingresos')),
                ('salida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='administrator.salidas')),
            ],
        ),
    ]
