# Generated by Django 5.1.4 on 2025-05-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_usuarios_centro_usuarios_ficha_usuarios_rol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='imagen',
            field=models.ImageField(db_column='ImagenUsuario', max_length=50, upload_to='users/'),
        ),
    ]
