# Generated by Django 5.1.4 on 2025-06-03 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_alter_usuarios_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('foto', models.ImageField(blank=True, max_length=50, null=True, upload_to='images/extras/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.usuarios')),
            ],
        ),
    ]
