# Generated by Django 5.1.4 on 2025-06-03 06:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_extras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extras',
            name='usuario',
        ),
        migrations.AddField(
            model_name='extras',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 3, 6, 4, 26, 377222), help_text='Fecha y hora en que se registró este objeto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extras',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='administrator.ingresos'),
        ),
        migrations.AddField(
            model_name='extras',
            name='observacion',
            field=models.TextField(blank=True, help_text='Observaciones adicionales (ej: objeto olvidado, dañado, verificado por seguridad)', null=True),
        ),
        migrations.AddField(
            model_name='extras',
            name='salio',
            field=models.BooleanField(default=True, help_text='Indica si el objeto salió con el usuario'),
        ),
        migrations.AlterField(
            model_name='extras',
            name='descripcion',
            field=models.CharField(help_text='Descripción del objeto extra (ej: maletín, caja de herramientas, laptop)', max_length=150),
        ),
        migrations.AlterField(
            model_name='extras',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto opcional del objeto extra', null=True, upload_to='images/extras/'),
        ),
    ]
