# Generated by Django 5.1.4 on 2025-06-03 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_remove_extras_usuario_extras_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extras',
            name='salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='administrator.salidas'),
        ),
        migrations.AlterField(
            model_name='extras',
            name='descripcion',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='extras',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='extras',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/extras/'),
        ),
        migrations.AlterField(
            model_name='extras',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extras',
            name='salio',
            field=models.BooleanField(default=True),
        ),
    ]
