# Generated by Django 5.1.4 on 2025-06-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_extras_salida_alter_extras_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extras',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='extras',
            name='salio',
        ),
        migrations.AlterField(
            model_name='extras',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
