# Generated by Django 5.2.1 on 2025-06-09 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_remove_extras_observacion_remove_extras_salio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDispositivo',
            fields=[
                ('dispositivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='administrator.dispositivos')),
                ('estado', models.CharField(choices=[('dentro', 'Dentro'), ('fuera', 'Fuera')], max_length=10)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
