# Generated by Django 5.2.1 on 2025-06-09 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_estadodispositivo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estadodispositivo',
            table='estado_dispositivo',
        ),
    ]
