# Generated by Django 5.1.4 on 2025-06-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_alter_estadodispositivo_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extras',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='extras/'),
        ),
    ]
